### ISSUE TITLE
Under load and multiple event loops dropwizard metrics can fail to register metrics

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-dropwizard-metrics#39] opened 2016-07-08 22:16 UTC
Version - 3.3.0

We have been doing some load testing on our server and were seeing some issues.  I reduced the test so that it was just testing a simple HTTP GET on a URL which produces a constant JSON payload in return.  When I run this under moderate load (400 clients, 1300 rps sustained) I see numerous exceptions, some clearly identifiable as being metric related, others with less information and the clients experience intermitant failures.  When I disable the vertx metrics all exceptions cease, as do the client errors.  Here are some samples:

```
22:05:21.907 [vert.x-eventloop-thread-3] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
22:05:22.087 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalArgumentException: vertx.http.servers.open-connections.127.0.0.1 is already used for a different type of metric
        at com.codahale.metrics.MetricRegistry.getOrAdd(MetricRegistry.java:325)
        at com.codahale.metrics.MetricRegistry.counter(MetricRegistry.java:115)
        at io.vertx.ext.dropwizard.impl.AbstractMetrics.counter(AbstractMetrics.java:113)
        at io.vertx.ext.dropwizard.impl.TCPMetricsImpl.connected(TCPMetricsImpl.java:62)
        at io.vertx.ext.dropwizard.impl.TCPMetricsImpl.connected(TCPMetricsImpl.java:31)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$createConnAndHandle$1(HttpServerImpl.java:707)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:234)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:706)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:570)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:522)
        at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:76)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
        at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1019)
        at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:990)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at java.lang.Thread.run(Thread.java:745)
22:05:22.088 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
```
```
22:06:02.504 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
        at io.vertx.ext.dropwizard.impl.TCPMetricsImpl.disconnected(TCPMetricsImpl.java:76)
        at io.vertx.ext.dropwizard.impl.TCPMetricsImpl.disconnected(TCPMetricsImpl.java:31)
        at io.vertx.core.net.impl.ConnectionBase.handleClosed(ConnectionBase.java:198)
        at io.vertx.core.http.impl.ServerConnection.handleClosed(ServerConnection.java:350)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:234)
        at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:97)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:238)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:217)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:238)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:217)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1315)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:238)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:887)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:732)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at java.lang.Thread.run(Thread.java:745)
```

The determining factor here appears to be the number of concurrent clients, moreso than the RPS (I did not see any issues unitl we started testing with a larger number of clients).

**Comment by vietj** [comment] 2016-07-08 22:22
it looks like a conflict in how vertx-dropwizard-metrics name things.

when this happen can you tell us what is the type of the metrics in the registry under the name vertx.http.servers.open-connections.127.0.0.1 ?

**Comment by sfitts** [comment] 2016-07-08 22:41
Unfortunately I haven't been able to reproduce somewhere that I can debug.  

Looking at the code however, I'm not sure it is a naming collision - rather I think it is a concurrency issue (which would make sense given it only happens under heavy connect/disconnect load).

Here is the code in dropwizard that is throwing the exception:

```
        final Metric metric = metrics.get(name);
        if (builder.isInstance(metric)) {
            return (T) metric;
        } else if (metric == null) {
            try {
                return register(name, builder.newMetric());
            } catch (IllegalArgumentException e) {
                final Metric added = metrics.get(name);
                if (builder.isInstance(added)) {
                    return (T) added;
                }
            }
        }
        throw new IllegalArgumentException(name + " is already used for a different type of metric");
```

Assume 2 threads running through this code using the same name you can get the exception if:

Both threads look for the metric and don't find it, so both make the decision to register it.  Both threads attempt to register it, one succeeds and the other fails, ending up in the catch block after the call to `register`.  At this point the metric exists and is of the correct type.  Now the first thread (the one that created it) proceeds onward does some work and then makes the decision to remove the metric.  If this happens *before* the second thread gets to execute the catch block then it will look for the metric, get a `null` return and as a result throw the exception at the bottom of the method.  The error message is a bit misleading because it isn't that the metric is the wrong type, it just isn't there when we thought it should be.

Couple this with the code at line 82 in `TCPMetricsImpl` and you have the ability to produce this problem.  Of course the likelihood of seeing this with 2 threads is extremely low, which is why it takes hundreds of clients to produce the problem.

This explains the first exception (the one in `connect`).

**Comment by vietj** [comment] 2016-07-08 22:49
so the problem would be that the endpoint metric is removed because we make some cleanup in:

public void closeEndpoint(String host, int port, EndpointMetric endpointMetric) {
  endpointMetric.close(clientReporter);
}

that callback should not remove the endpoint OR the creation of endpoint should retry on an IllegalArgumentException when this happens ?

**Comment by sfitts** [comment] 2016-07-08 22:49
As for the NPE in `disconnected` -- here is the line of code:

`connections.update(System.nanoTime() - ctx, TimeUnit.NANOSECONDS);`

The only way for this to NPE is for either `connections` or `ctx` to be null.  I don't see a way for `connections` to be null (it is initialized in the constructor and never changed thereafter), so it seems it must be `ctx`.  This is a Long passed as a parameter to disconnected from line 198 of `ConnectionBase`.  Here we are getting the value from the call to `metric()` which is basically just used to store the return result from `connected`.  Given this I'm guessing that if we fix the issue above, this one will simply go away.

**Comment by vietj** [comment] 2016-07-08 22:55
can you try your tests again and comment line `reporter.remove("endpoint", name);` in `EndpointMetric` ?

**Comment by sfitts** [comment] 2016-07-08 22:55
>so the problem would be that the endpoint metric is removed because we make some cleanup in:
>
>public void closeEndpoint(String host, int port, EndpointMetric endpointMetric) {
>  endpointMetric.close(clientReporter);
>}
>
>that callback should not remove the endpoint OR the creation of endpoint should retry on an >IllegalArgumentException when this happens ?

Not sure about the cleanup here, but the code in `TCPMetricsImpl.disconnected` also removes the metric if the count is 0.  I'm not sure we need to remove the metric in that case (it is probably OK to have a count that is 0), but if you do then yes, you'll have to retry the `getOrAdd` calls.

The DW framework doesn't expect metrics to come and go so it doesn't synchronize any of those operations (it uses a concurrent map to hold all the metrics, that that's as far as it goes).

**Comment by sfitts** [comment] 2016-07-08 22:57
I can try that once I have the time to set things up so I can use a locally built version of the libraries (something I need to so in any case).  I will give that a try over the weekend (need to complete some other testing I'm doing today).

**Comment by vietj** [comment] 2016-07-08 22:58
ok, looking forward from your feedback, thanks

**Comment by vietj** [comment] 2016-07-09 12:26
how many vertx client instances do you deploy by the way ?

**Comment by vietj** [comment] 2016-07-09 13:38
I think it does not make sense to remove endpoint metrics when an endpoint is not connected anymore (i.e business wise) - therefore I'm proposing to not remove the endpoint metrics and instead to have a list of monitored endpoints `$host:$port` similar to other monitored metrics.

**Comment by vietj** [comment] 2016-07-09 13:41
I've commited this change : https://github.com/vert-x3/vertx-dropwizard-metrics/commit/de87ee4f232d9a78b101e759580685a520249578

would you mind to review it and possibly test it ?

**Comment by sfitts** [comment] 2016-07-09 15:10
In the tests I'm running the client's are Vertx so none.  Regarding the endpoint metrics, that makes sense, but the problem here is being caused by the server side TCPMetrics (which also add and remove metrics during connected/disconnected).  So the pattern is the same, but it is a different chunk of code.

**Comment by vietj** [comment] 2016-07-09 15:21
@sfitts I mean how many instances of the verticle creating an HttpClient are you deploying ?

**Comment by vietj** [comment] 2016-07-09 15:22
ah right it is in server - I worked to fix similar issue in client - never mind

**Comment by vietj** [comment] 2016-07-09 15:23
so how many instances of your server are you deploying ?

**Comment by sfitts** [comment] 2016-07-09 15:23
In this test -- none.  I have 4 instances of a verticle creating an HttpServer, but none creating HttpClient (we do have verticles that create HttpClient instances, but none of those are being used here).

Yep -- the same pattern is being used on both sides (which stands to reason).

**Comment by vietj** [comment] 2016-07-09 15:24
I don't know why I focused on EndpointMetric ...

**Comment by vietj** [comment] 2016-07-09 15:24
I will do a similar testup and use an http client to try to reproduce it asap.

(I was able to reproduce for the EndpointMetric).

**Comment by vietj** [comment] 2016-07-09 15:29
400 clients opening each 1 connection ? i.e 400 connections ?

**Comment by vietj** [comment] 2016-07-09 15:32
are the client using keep-alive ?

**Comment by sfitts** [comment] 2016-07-09 15:38
The clients are python, using the requests library.  So they are pooling and using keep alive (though they are 1.1 so that's the norm).  Each client issues a GET request every 100ms.

**Comment by vietj** [comment] 2016-07-09 15:41
I'm able to reproduce these issues :

```
Unhandled exception 
java.lang.IllegalArgumentException: vertx.http.servers.open-connections.127.0.0.1 is already used for a different type of metric
	at com.codahale.metrics.MetricRegistry.getOrAdd(MetricRegistry.java:325)
	at com.codahale.metrics.MetricRegistry.counter(MetricRegistry.java:115)
	at io.vertx.ext.dropwizard.impl.AbstractMetrics.counter(AbstractMetrics.java:113)
	at io.vertx.ext.dropwizard.impl.TCPMetricsImpl.connected(TCPMetricsImpl.java:62)
	at io.vertx.ext.dropwizard.impl.TCPMetricsImpl.connected(TCPMetricsImpl.java:31)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$createConnAndHandle$1(HttpServerImpl.java:707)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:234)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:706)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:570)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:522)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:76)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1019)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:990)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)

Unhandled exception 
java.lang.NullPointerException
	at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:298)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:424)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:139)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:615)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:522)
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:234)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1019)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:990)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)

Unhandled exception 
java.lang.IllegalArgumentException: vertx.http.servers.open-connections.127.0.0.1 is already used for a different type of metric
	at com.codahale.metrics.MetricRegistry.getOrAdd(MetricRegistry.java:325)
	at com.codahale.metrics.MetricRegistry.counter(MetricRegistry.java:115)
	at io.vertx.ext.dropwizard.impl.AbstractMetrics.counter(AbstractMetrics.java:113)
	at io.vertx.ext.dropwizard.impl.TCPMetricsImpl.connected(TCPMetricsImpl.java:62)
	at io.vertx.ext.dropwizard.impl.TCPMetricsImpl.connected(TCPMetricsImpl.java:31)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$createConnAndHandle$1(HttpServerImpl.java:707)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:234)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:706)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:570)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:522)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:76)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1019)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:990)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)

Unhandled exception 
java.lang.NullPointerException
	at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:298)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:424)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:139)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:615)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:522)
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:234)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1019)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:990)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vietj** [comment] 2016-07-09 15:41
looks similar to what you have

**Comment by sfitts** [comment] 2016-07-09 15:41
Yep -- that's it.

**Comment by vietj** [comment] 2016-07-09 15:42
thanks your responsiveness is helpful - I'm going to investigate these - will keep you informed

**Comment by sfitts** [comment] 2016-07-09 15:46
No problem -- let me know if I can be of any more help.

**Comment by vietj** [comment] 2016-07-09 15:51
I think you pretty much nailed down the problem with the `getOrAdd`

it looks to me the simplest and safest option at the moment is to do:

```
  protected Counter counter(String... names) {
    try {
      return registry.counter(nameOf(names));
    } catch (Exception e) {
      return new Counter();
    }
  }
```

**Comment by sfitts** [comment] 2016-07-09 15:58
Hmm.. that would mean that we'd end up with metrics that weren't part of the registry.  But you are right, as a backstop to ensure the code doesn't produce errors it is the best alternative.  I think we still want to avoid doing removes in high volume code paths (like the one above) to futher limit the times when this becomes an issue.

**Comment by vietj** [comment] 2016-07-09 16:16
I've done some tests and this happens rarely using non keep-alive connections to maximize the chance to happen, with keep-alive I don't see it. So the side effect is to lose a small fraction of reported metrics.

The removal are related to the design of how Dropwizard Metrics is used. There is no good way to avoid removals as the reporting uses the socket remote address and thus must be cleaned up at some point.

In the particular case we are fixing, it happens because we are load testing from the same host (127.0.0.1), in reality the remote address will be differents.

**Comment by vietj** [comment] 2016-07-09 16:36
I pushed the fix - if you can try it's great :-)

**Closed** 2016-07-09 16:36 UTC
