### ISSUE TITLE
metricsService.getMetricsSnapshot(vertx) return null when redeploy is enabled.

### ISSUE THREAD

**Issue by bckfnn** [vert-x3/vertx-dropwizard-metrics#2] opened 2015-04-07 14:54 UTC
Example java project:

https://github.com/bckfnn/vertx-metrics-test

Watch the line stdout "metrics json in verticle" which print null when redeploy is enabled. It return the correct metrics data when redeploy is disabled.

The AbstractMetrics class seem to get loaded twice, both with the AppClassLoader and with the IsolationClassLoader.

**Comment by vietj** [comment] 2015-06-21 17:01
ok will investigate soon

**Comment by vietj** [comment] 2015-06-21 20:51
This is due to a classloading issue in Vert.x core not a bug in metrics per se, I will send an email on the vertx-dev list about it, since I fixed a similar issue with vertx-lang-groovy last week. I believe it's worth discussing before 3.0

**Comment by purplefox** [comment] 2015-06-23 09:31
can i close this now?

**Comment by vietj** [comment] 2015-06-23 10:16
yes

**Closed** 2015-06-23 12:44 UTC
Labels: Planned
